### ISSUE TITLE
Printer not recognized, barcode scanner support.

### ISSUE THREAD

**Issue by marcogaio** [pywebdriver/pywebdriver#150]
I've discovered and give a try to pywebdriver, trying to simplify a bit my setup and stop using a bunch of RPi with posbox.

I've installed the package, but seems does not recognize at all my printer and my barcode scanner.

Printer is an ESC/POS compatible printer that work perfectly with posbox; also barcode scanner works as expected.

Attached USB report. What i can do to debug and fix that issue?

Thanks.
![Schermata a 2024-05-30 22-57-46](https://github.com/pywebdriver/pywebdriver/assets/7048664/1d0e7fda-f2f5-4228-b5c2-1412f3555889)

**Comment by marcogaio** [comment]
OK, some more info; with the help of some googling i've found some hint and finally produced that patch:

```
--- /opt/venvs/pywebdriver/lib/python3.8/site-packages/pywebdriver/plugins/escpos_driver.py.dist	2024-06-01 18:08:15.868454233 +0200
+++ /opt/venvs/pywebdriver/lib/python3.8/site-packages/pywebdriver/plugins/escpos_driver.py	2024-06-02 17:39:31.579765699 +0200
@@ -61,6 +61,7 @@
     {"vendor": 0x04B8, "product": 0x0E15, "name": "Epson TM-T20II"},
     {"vendor": 0x04B8, "product": 0x0E28, "name": "Epson TM-T20III"},
     {"vendor": 0x0525, "product": 0xA700, "name": "Netchip POS Printer Aures ODP 333"},
+    {"vendor": 0x0471, "product": 0x0055, "name": "Philips (or NXP) POS Printer"},
 ]
 
 _logger = logging.getLogger(__name__)
@@ -170,7 +171,7 @@
                     idProduct = printer.get("product")
                     usb_args = {"idVendor": idVendor, "idProduct": idProduct}
                     kwargs["in_ep"] = printer.get("in_ep", 0x82)
-                    kwargs["out_ep"] = printer.get("out_ep", 0x01)
+                    kwargs["out_ep"] = printer.get("out_ep", 0x02)
                     kwargs["timeout"] = 0
                     POSDriver.__init__(self, idVendor, idProduct, **kwargs)
                     self.open_args.append(usb_args)  # First open_arg is usb_args
```

First statement add support for vendor/ID of my printer; second statement change endpoint out address from the default 1 to 2. In this way, printer et correctly recognized, but remain offline/in error; claim conflict with usbfs and if i try to print i catch:

```
Jun  2 18:08:21 tocco pywebdriverd[53136]: INFO:werkzeug:192.168.9.56 - - [02/Jun/2024 18:08:21] "OPTIONS /hw_proxy/print_xml_receipt?session_id= HTTP/1.1" 200 -
Jun  2 18:08:21 tocco pywebdriverd[53136]: INFO:werkzeug:192.168.9.56 - - [02/Jun/2024 18:08:21] "POST /hw_proxy/print_xml_receipt?session_id= HTTP/1.1" 200 -
Jun  2 18:08:21 tocco kernel: [ 3281.522107] usb 3-2: usbfs: interface 0 claimed by usbfs while 'pywebdriverd' sets config #1
Jun  2 18:08:21 tocco pywebdriverd[53136]: ERROR:pywebdriver:[Errno 16] Resource busy
Jun  2 18:08:21 tocco pywebdriverd[53136]: ------------------------------------------------------------
Jun  2 18:08:21 tocco pywebdriverd[53136]: Traceback (most recent call last):
Jun  2 18:08:21 tocco pywebdriverd[53136]:   File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/pywebdriver/plugins/base_driver.py", line 107, in run
Jun  2 18:08:21 tocco pywebdriverd[53136]:     self.process_task(task, timestamp, data)
Jun  2 18:08:21 tocco pywebdriverd[53136]:   File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/pywebdriver/plugins/base_driver.py", line 95, in process_task
Jun  2 18:08:21 tocco pywebdriverd[53136]:     return getattr(self, task)(data)
Jun  2 18:08:21 tocco pywebdriverd[53136]:   File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/pywebdriver/plugins/escpos_driver.py", line 298, in receipt
Jun  2 18:08:21 tocco pywebdriverd[53136]:     Layout(content).format(self)
Jun  2 18:08:21 tocco pywebdriverd[53136]:   File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/xmlescpos/layout.py", line 563, in format
Jun  2 18:08:21 tocco pywebdriverd[53136]:     printer._raw(SHEET_ROLL_MODE)
Jun  2 18:08:21 tocco pywebdriverd[53136]:   File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/escpos/printer.py", line 100, in _raw
Jun  2 18:08:21 tocco pywebdriverd[53136]:     self.device.write(self.out_ep, msg, self.timeout)
Jun  2 18:08:21 tocco pywebdriverd[53136]:   File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/core.py", line 986, in write
Jun  2 18:08:21 tocco pywebdriverd[53136]:     intf, ep = self._ctx.setup_request(self, endpoint)
Jun  2 18:08:21 tocco pywebdriverd[53136]:   File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/core.py", line 113, in wrapper
Jun  2 18:08:21 tocco pywebdriverd[53136]:     return f(self, *args, **kwargs)
Jun  2 18:08:21 tocco pywebdriverd[53136]:   File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/core.py", line 229, in setup_request
Jun  2 18:08:21 tocco pywebdriverd[53136]:     self.managed_claim_interface(device, intf)
Jun  2 18:08:21 tocco pywebdriverd[53136]:   File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/core.py", line 113, in wrapper
Jun  2 18:08:21 tocco pywebdriverd[53136]:     return f(self, *args, **kwargs)
Jun  2 18:08:21 tocco pywebdriverd[53136]:   File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/core.py", line 178, in managed_claim_interface
Jun  2 18:08:21 tocco pywebdriverd[53136]:     self.backend.claim_interface(self.handle, i)
Jun  2 18:08:21 tocco pywebdriverd[53136]:   File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/backend/libusb1.py", line 829, in claim_interface
Jun  2 18:08:21 tocco pywebdriverd[53136]:     _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
Jun  2 18:08:21 tocco pywebdriverd[53136]:   File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/backend/libusb1.py", line 604, in _check
Jun  2 18:08:21 tocco pywebdriverd[53136]:     raise USBError(_strerror(ret), ret, _libusb_errno[ret])
Jun  2 18:08:21 tocco pywebdriverd[53136]: usb.core.USBError: [Errno 16] Resource busy
Jun  2 18:08:21 tocco pywebdriverd[53136]: ------------------------------------------------------------
```

googling again a bit, seems to me that there's a conflict between python-usb library and the rest of the system; i've tried some hint (unload some modules/services, ...) but nothing help.

Someone can provide some feedback? Thanks.

**Comment by marcogaio** [comment]
OK, worked. Simply **THAT** particular ESC/Pos printer does not work, but other (that have __out_ep__ address even different, __0x03__), worked.

By some week i've to unpack and test all the printer, so i'll provide a patch with all USB VENDOR:MODEL listed, and some notes.

Still seeking some feedback, thanks.

**Comment by quentinDupont** [comment]
Sorry i'm not enough skilful to help you on that.. thanks for the work !

**Comment by marcogaio** [comment]
Some report after a bit of time:

1. some printer does NOT work at all
2. some printer work __one shot__: if i restart pywebdriver, they print a recipe, then stop working
3. some print __seems__ to work, but are very unreilable: they print 2-3 recipes, then start print ascii garbage, then after some print came back and print well.

I use only __compatible/no_brand__ printers, so probably it is also a printer trouble, but **ALL** that printers works with POSBox and most of these works with IoTBox.

I've no python skills, so i'm giving up; if you think i can be useful doing some test, ping me here.

**Comment by legalsylvain** [comment]
Hi @marcogaio, what is the version of Odoo you are using ? 

If it's a 16+, and if your cash register PC is on linux, maybe you can try another tool I develop recently, named "Odoo Drivers". See : https://gitlab.com/grap-rhone-alpes/odoo-driver/-/tree/main?ref_type=heads#odoo-drivers

If so, you'll have to patch this line. https://gitlab.com/grap-rhone-alpes/odoo-driver/-/blob/main/odoo_driver/usb_device/usb_device_list.py?ref_type=heads#L12

Regards.

**Comment by marcogaio** [comment]
After some time, i come back @legalsylvain. I've tried odoo-driver, but i've hit more ore less the same trouble.

See there, just opened a bug report...
